/**
 * Reads public/images/ recursively and emits a `gallerySections.ts` data file
 * reflecting every actual image folder on disk.
 *
 * Run with: pnpm tsx scripts/generate-gallery.ts
 *
 * Pills always use the EXACT folder name (the leaf folder, if nested).
 * Section order is controlled by SECTION_ORDER below; unknown folders are
 * appended at the end alphabetically. Curated section descriptions live in
 * SECTION_DESCRIPTIONS; folders without an entry get a generic fallback.
 */
import { readdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const IMAGES_DIR = fileURLToPath(new URL("../public/images", import.meta.url));
const OUTPUT_FILE = fileURLToPath(
  new URL("../src/data/gallerySections.ts", import.meta.url)
);

const IMAGE_EXTS = new Set([".webp", ".jpg", ".jpeg", ".png"]);

interface DiscoveredFolder {
  /** Folder name shown on the pill (leaf folder, e.g. "Blue Room"). */
  name: string;
  /** Path under public/images, e.g. "Bedrooms/Blue Room". */
  relPath: string;
  /** Image filenames in this folder. */
  files: string[];
}

// Optional curated descriptions. Keys are leaf folder names. Without an entry,
// a generic "A look at the <folder>." description is used.
const SECTION_DESCRIPTIONS: Record<string, string> = {
  Exterior: "Curb-side first impressions and dusk-lit facades.",
  Patio: "Hot tub, outdoor seating, and woodland surrounds.",
  "Living Room": "Open-plan seating with warm textures and natural light.",
  Kitchen: "Modern appliances, ample counter space, and a chef-friendly layout.",
  "Dining Area": "A statement table that brings the whole group together.",
  "Blue Room": "Calming palette with a queen bed and plush bedding.",
  "Clay Room": "Earthy tones and warm bedding for a restful retreat.",
  "Green Room": "Nature-inspired suite with garden views and a queen bed.",
  "Purple Room": "Layered textiles and a king bed for restful nights.",
  Bathroom: "Spa-inspired finishes and polished tile.",
  Hallway: "Architectural lines connecting the home's living spaces.",
  Amenities: "Hot tub, smart TV, and the comforts that make stays effortless.",
};

// Display order. Leaf folder names matching here come first in that order;
// anything else is appended alphabetically.
const SECTION_ORDER = [
  "Exterior",
  "Patio",
  "Living Room",
  "Kitchen",
  "Dining Area",
  "Amenities",
  "Blue Room",
  "Clay Room",
  "Green Room",
  "Purple Room",
  "Bathroom",
  "Hallway",
];

const toId = (folder: string) =>
  folder
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

async function discover(currentRel = ""): Promise<DiscoveredFolder[]> {
  const abs = join(IMAGES_DIR, currentRel);
  const entries = await readdir(abs, { withFileTypes: true });

  const files: string[] = [];
  const dirs: string[] = [];

  for (const entry of entries) {
    if (entry.name === ".DS_Store") continue;
    if (entry.isDirectory()) {
      dirs.push(entry.name);
    } else if (entry.isFile()) {
      const lower = entry.name.toLowerCase();
      if ([...IMAGE_EXTS].some((ext) => lower.endsWith(ext))) {
        files.push(entry.name);
      }
    }
  }

  const results: DiscoveredFolder[] = [];

  // A folder with images becomes its own section (the leaf-name pattern).
  // Only top-level loose files (hero-image.png, property-main.png) are
  // ignored — they're not bedroom photos.
  if (currentRel !== "" && files.length > 0) {
    const segments = currentRel.split("/");
    results.push({
      name: segments[segments.length - 1],
      relPath: currentRel,
      files: files.sort((a, b) =>
        a.localeCompare(b, undefined, { numeric: true })
      ),
    });
  }

  for (const dir of dirs.sort()) {
    const nestedRel = currentRel ? `${currentRel}/${dir}` : dir;
    const nested = await discover(nestedRel);
    results.push(...nested);
  }

  return results;
}

async function main() {
  const all = await discover();

  const orderIndex = (name: string) => {
    const idx = SECTION_ORDER.indexOf(name);
    return idx === -1 ? Number.MAX_SAFE_INTEGER : idx;
  };

  const ordered = all.sort((a, b) => {
    const ai = orderIndex(a.name);
    const bi = orderIndex(b.name);
    if (ai !== bi) return ai - bi;
    return a.name.localeCompare(b.name);
  });

  const formatted = ordered
    .map((folder) => {
      const description =
        SECTION_DESCRIPTIONS[folder.name] ??
        `A look at the ${folder.name.toLowerCase()}.`;
      const paths = folder.files.map((file) => `${folder.relPath}/${file}`);
      return `  section(${JSON.stringify(toId(folder.name))}, ${JSON.stringify(folder.name)}, ${JSON.stringify(description)}, [\n${paths
        .map((p) => `    ${JSON.stringify(p)},`)
        .join("\n")}\n  ]),`;
    })
    .join("\n");

  const fileContents = `// AUTO-GENERATED by scripts/generate-gallery.ts — re-run after adding new images.
const baseBlobUrl =
  "https://xfrcwgafqy20sjqa.public.blob.vercel-storage.com/images";

const toBlobUrl = (path: string) => {
  const encoded = path
    .split("/")
    .map((segment) => encodeURIComponent(segment))
    .join("/");
  return \`\${baseBlobUrl}/\${encoded}\`;
};

export type GallerySection = {
  id: string;
  name: string;
  description: string;
  cover: string;
  images: string[];
};

const section = (
  id: string,
  name: string,
  description: string,
  paths: string[]
): GallerySection => ({
  id,
  name,
  description,
  cover: toBlobUrl(paths[0]),
  images: paths.map(toBlobUrl),
});

export const gallerySections: GallerySection[] = [
${formatted}
];
`;

  await writeFile(OUTPUT_FILE, fileContents, "utf8");
  console.log(`✓ Wrote ${ordered.length} sections to ${OUTPUT_FILE}`);
  for (const folder of ordered) {
    console.log(`  ${folder.name}: ${folder.files.length} image${folder.files.length === 1 ? "" : "s"} (${folder.relPath})`);
  }
}

main().catch((error) => {
  console.error("Generation failed:", error);
  process.exit(1);
});
