/**
 * Reads public/images/ and emits a `gallerySections.ts` data file
 * reflecting every actual image file on disk.
 *
 * Run with: pnpm tsx scripts/generate-gallery.ts
 *
 * Section order, labels, and descriptions live in SECTION_META below.
 * Folders not listed in SECTION_META are appended at the end with a
 * generated label and a TODO description for the owner to refine.
 */
import { readdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const IMAGES_DIR = fileURLToPath(new URL("../public/images", import.meta.url));
const OUTPUT_FILE = fileURLToPath(
  new URL("../src/data/gallerySections.ts", import.meta.url)
);

const IMAGE_EXTS = new Set([".webp", ".jpg", ".jpeg", ".png"]);

interface SectionMeta {
  id: string;
  name: string;
  description: string;
}

const SECTION_META: Record<string, SectionMeta> = {
  Front: {
    id: "exterior",
    name: "Exterior",
    description: "Curb-side first impressions and dusk-lit facades.",
  },
  Patio: {
    id: "patio",
    name: "Patio & Outdoor",
    description: "Hot tub, outdoor seating, and woodland surrounds.",
  },
  "Living Room": {
    id: "living-room",
    name: "Living Room",
    description: "Open-plan seating with warm textures and natural light.",
  },
  Kitchen: {
    id: "kitchen",
    name: "Kitchen",
    description: "Modern appliances, ample counter space, and a chef-friendly layout.",
  },
  "Dining Area": {
    id: "dining-area",
    name: "Dining Area",
    description: "A statement table that brings the whole group together.",
  },
  "Blue Room": {
    id: "blue-room",
    name: "Blue Room",
    description: "Calming palette with a queen bed and plush bedding.",
  },
  "Green Room": {
    id: "green-room",
    name: "Green Room",
    description: "Nature-inspired suite with garden views and a queen bed.",
  },
  "Orange Room": {
    id: "orange-room",
    name: "Orange Room",
    description: "Sunny accents and playful lighting.",
  },
  "Purple Room": {
    id: "purple-room",
    name: "Purple Room",
    description: "Layered textiles and a king bed for restful nights.",
  },
  Bathrooms: {
    id: "bathrooms",
    name: "Bathrooms",
    description: "Spa-inspired finishes and polished tile across both bathrooms.",
  },
  Hallway: {
    id: "hallway",
    name: "Hallway",
    description: "Architectural lines connecting the home's living spaces.",
  },
  Garage: {
    id: "garage",
    name: "Garage",
    description: "Covered parking and additional storage.",
  },
};

const SECTION_ORDER = [
  "Front",
  "Patio",
  "Living Room",
  "Kitchen",
  "Dining Area",
  "Blue Room",
  "Green Room",
  "Orange Room",
  "Purple Room",
  "Bathrooms",
  "Hallway",
  "Garage",
];

async function listImagesInFolder(folder: string): Promise<string[]> {
  const fullPath = join(IMAGES_DIR, folder);
  const entries = await readdir(fullPath, { withFileTypes: true });
  return entries
    .filter((entry) => entry.isFile())
    .filter((entry) => entry.name !== ".DS_Store")
    .filter((entry) => {
      const lower = entry.name.toLowerCase();
      return [...IMAGE_EXTS].some((ext) => lower.endsWith(ext));
    })
    .map((entry) => entry.name)
    .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));
}

async function main() {
  const entries = await readdir(IMAGES_DIR, { withFileTypes: true });
  const folders = entries
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name);

  const ordered = [
    ...SECTION_ORDER.filter((name) => folders.includes(name)),
    ...folders.filter((name) => !SECTION_ORDER.includes(name)),
  ];

  const sections: Array<{
    meta: SectionMeta;
    paths: string[];
  }> = [];

  for (const folder of ordered) {
    const images = await listImagesInFolder(folder);
    if (images.length === 0) continue;
    const meta =
      SECTION_META[folder] ??
      ({
        id: folder.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
        name: folder,
        description: `TODO: write a one-line description for "${folder}".`,
      } satisfies SectionMeta);
    sections.push({
      meta,
      paths: images.map((file) => `${folder}/${file}`),
    });
  }

  const formatted = sections
    .map(
      ({ meta, paths }) =>
        `  section(${JSON.stringify(meta.id)}, ${JSON.stringify(meta.name)}, ${JSON.stringify(meta.description)}, [\n${paths
          .map((p) => `    ${JSON.stringify(p)},`)
          .join("\n")}\n  ]),`
    )
    .join("\n");

  const fileContents = `// AUTO-GENERATED by scripts/generate-gallery.ts — re-run after adding new images.
const baseBlobUrl =
  "https://xfrcwgafqy20sjqa.public.blob.vercel-storage.com/images";

const toBlobUrl = (path: string) => {
  const encoded = path
    .split("/")
    .map((segment) => encodeURIComponent(segment))
    .join("/");
  return \`\${baseBlobUrl}/\${encoded}\`;
};

export type GallerySection = {
  id: string;
  name: string;
  description: string;
  cover: string;
  images: string[];
};

const section = (
  id: string,
  name: string,
  description: string,
  paths: string[]
): GallerySection => ({
  id,
  name,
  description,
  cover: toBlobUrl(paths[0]),
  images: paths.map(toBlobUrl),
});

export const gallerySections: GallerySection[] = [
${formatted}
];
`;

  await writeFile(OUTPUT_FILE, fileContents, "utf8");
  console.log(`✓ Wrote ${sections.length} sections to ${OUTPUT_FILE}`);
  for (const { meta, paths } of sections) {
    console.log(`  ${meta.name}: ${paths.length} image${paths.length === 1 ? "" : "s"}`);
  }
}

main().catch((error) => {
  console.error("Generation failed:", error);
  process.exit(1);
});
