// AUTO-GENERATED by scripts/generate-gallery.ts — re-run after adding new images.
const baseBlobUrl =
  "https://xfrcwgafqy20sjqa.public.blob.vercel-storage.com/images";

const toBlobUrl = (path: string) => {
  const encoded = path
    .split("/")
    .map((segment) => encodeURIComponent(segment))
    .join("/");
  return `${baseBlobUrl}/${encoded}`;
};

export type GallerySection = {
  id: string;
  name: string;
  description: string;
  cover: string;
  images: string[];
};

const section = (
  id: string,
  name: string,
  description: string,
  paths: string[]
): GallerySection => ({
  id,
  name,
  description,
  cover: toBlobUrl(paths[0]),
  images: paths.map(toBlobUrl),
});

export const gallerySections: GallerySection[] = [
  section("exterior", "Exterior", "Curb-side first impressions and dusk-lit facades.", [
    "Exterior/CasaBlanca-23 Photoshopped.png",
    "Exterior/CasaBlanca-28.png",
    "Exterior/CasaBlanca-33.png",
    "Exterior/CasaBlanca-94.png",
    "Exterior/CasaBlanca-95 photoshopped.png",
    "Exterior/hero-image.png",
  ]),
  section("patio", "Patio", "Hot tub, outdoor seating, and woodland surrounds.", [
    "Patio/CasaBlanca-12.png",
    "Patio/CasaBlanca-14.png",
    "Patio/CasaBlanca-76.png",
    "Patio/CasaBlanca-77.png",
    "Patio/CasaBlanca-81.png",
    "Patio/CasaBlanca-82.png",
  ]),
  section("living-room", "Living Room", "Open-plan seating with warm textures and natural light.", [
    "Living Room/CasaBlanca-17.png",
    "Living Room/CasaBlanca-31.png",
    "Living Room/CasaBlanca-51.png",
    "Living Room/CasaBlanca-53.png",
    "Living Room/CasaBlanca-101.png",
    "Living Room/Ocala House -31.webp",
    "Living Room/Ocala House -35.webp",
  ]),
  section("kitchen", "Kitchen", "Modern appliances, ample counter space, and a chef-friendly layout.", [
    "Kitchen/CasaBlanca-11.png",
    "Kitchen/CasaBlanca-18.png",
    "Kitchen/CasaBlanca-30.png",
    "Kitchen/CasaBlanca-67.png",
    "Kitchen/CasaBlanca-105.png",
    "Kitchen/Ocala House -32.webp",
    "Kitchen/Ocala House -33.webp",
  ]),
  section("dining-area", "Dining Area", "A statement table that brings the whole group together.", [
    "Dining Area/CasaBlanca-70.png",
    "Dining Area/CasaBlanca-71.png",
    "Dining Area/CasaBlanca-72.png",
    "Dining Area/CasaBlanca-73.png",
    "Dining Area/CasaBlanca-74.png",
    "Dining Area/CasaBlanca-75.png",
    "Dining Area/CasaBlanca-103.png",
    "Dining Area/CasaBlanca-104.png",
    "Dining Area/CasaBlanca-106.png",
    "Dining Area/Ocala House -34.webp",
  ]),
  section("amenities", "Amenities", "Hot tub, smart TV, and the comforts that make stays effortless.", [
    "Amenities/CasaBlanca-12.png",
    "Amenities/CasaBlanca-29.png",
    "Amenities/CasaBlanca-36.png",
    "Amenities/CasaBlanca-37.png",
    "Amenities/CasaBlanca-38.png",
    "Amenities/CasaBlanca-39.png",
    "Amenities/CasaBlanca-41.png",
    "Amenities/CasaBlanca-43.png",
    "Amenities/CasaBlanca-79.png",
  ]),
  section("blue-room", "Blue Room", "Calming palette with a queen bed and plush bedding.", [
    "Bedrooms/Blue Room/CasaBlanca-4.png",
    "Bedrooms/Blue Room/CasaBlanca-10.png",
    "Bedrooms/Blue Room/CasaBlanca-65.png",
    "Bedrooms/Blue Room/CasaBlanca-66.png",
    "Bedrooms/Blue Room/CasaBlanca-99.png",
  ]),
  section("clay-room", "Clay Room", "Earthy tones and warm bedding for a restful retreat.", [
    "Bedrooms/Clay Room/CasaBlanca-61.png",
    "Bedrooms/Clay Room/CasaBlanca-62.png",
    "Bedrooms/Clay Room/CasaBlanca-63.png",
    "Bedrooms/Clay Room/CasaBlanca-64.png",
    "Bedrooms/Clay Room/CasaBlanca-92.png",
    "Bedrooms/Clay Room/CasaBlanca-97.png",
    "Bedrooms/Clay Room/CasaBlanca-98.png",
  ]),
  section("green-room", "Green Room", "Nature-inspired suite with garden views and a queen bed.", [
    "Bedrooms/Green Room/CasaBlanca-57.png",
    "Bedrooms/Green Room/CasaBlanca-59 (1).png",
    "Bedrooms/Green Room/Ocala House -11.webp",
    "Bedrooms/Green Room/Ocala House -12.webp",
    "Bedrooms/Green Room/Ocala House .webp",
  ]),
  section("purple-room", "Purple Room", "Layered textiles and a king bed for restful nights.", [
    "Bedrooms/Purple Room/CasaBlanca-44.png",
    "Bedrooms/Purple Room/CasaBlanca-45.png",
    "Bedrooms/Purple Room/CasaBlanca-46.png",
    "Bedrooms/Purple Room/CasaBlanca-47.png",
    "Bedrooms/Purple Room/CasaBlanca-49.png",
    "Bedrooms/Purple Room/CasaBlanca-50.png",
    "Bedrooms/Purple Room/Ocala House -21.webp",
    "Bedrooms/Purple Room/Ocala House -24.webp",
    "Bedrooms/Purple Room/Ocala House -25.webp",
  ]),
  section("bathroom", "Bathroom", "Spa-inspired finishes and polished tile.", [
    "Bathroom/CasaBlanca-54.png",
    "Bathroom/CasaBlanca-55.png",
    "Bathroom/CasaBlanca-56.png",
    "Bathroom/Ocala House -1.webp",
    "Bathroom/Ocala House -3.webp",
  ]),
  section("hallway", "Hallway", "Architectural lines connecting the home's living spaces.", [
    "Hallway/Ocala House -6.webp",
    "Hallway/Ocala House -7.webp",
    "Hallway/Ocala House -37.webp",
    "Hallway/Ocala House -38.webp",
  ]),
];
